  name: Run Pre-Commit Hooks

  description: Run pre-commit hooks

  inputs:
    check-type:
      description: The type of check to run. Valid values are "all", "common", "terraform", "golang", and "renovate"
      required: true
      default: all

  runs:
    using: composite
    steps:
      - name: Init pre-commit cache
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.cache/pre-commit"
          key: "pre-commit-${{inputs.check-type}}"

      - name: Init docker cache
        id: init-docker-cache
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.cache/docker"
          key: docker|${{ hashFiles('Makefile') }}

      - name: Docker save build harness
        if: steps.init-docker-cache.outputs.cache-hit != 'true'
        run: make docker-save-build-harness

      - name: Load build harness
        run: make docker-load-build-harness

      - name: Run `pre-commit run -a`
        run: "make pre-commit-${{inputs.check-type}} fix-cache-permissions"
