vars:
  stage: "dev"
  region: "us-gov-west-1"
  ami_id: "ami-08b9131e91f9f6c69"
  test_var: "{{ \"Hello, Atmos!\" }}"

components:
  terraform:
    vpc:
      vars:
        name: "dev-vpc"
        vpc_cidr: "10.200.0.0/16"
        secondary_cidr_blocks: ["100.64.0.0/16"]
        private_subnets:
          - "10.200.12.0/22"
          - "10.200.16.0/22"
          - "10.200.20.0/22"
        database_subnets:
          - "10.200.24.0/27"
          - "10.200.24.32/27"
          - "10.200.24.64/27"
        azs:
          - "us-gov-west-1a"
          - "us-gov-west-1b"
          - "us-gov-west-1c"
        single_nat_gateway: false
        enable_nat_gateway: false
        tags:
          Environment: "dev"
          Project: "example"
          Owner: "team"
          ManagedBy: "Terraform"
          Repo: "https://github.com/defenseunicorns/terraform-aws-vpc"
    bastion:
      dependencies:
        terraform:
          - vpc  # Ensure vpc runs before bastion
      vars:
        name: "dev-bastion"
        vpc_id: '{{ (atmos.Component "vpc" "dev").outputs.vpc_id }}'
        instance_type: "t3.micro"
        subnet_id: '{{ index (atmos.Component "vpc" .stack).outputs.private_subnets 0 }}'
        tags:
          Environment: "dev"
          Owner: "team"
    eks:
      vars:
        cluster_name: "dev-eks"
        private_subnet_ids: '{{ (atmos.Component "vpc" .stack).outputs.private_subnets | toJson  }}'
        control_plane_subnet_ids: '{{ (atmos.Component "vpc" .stack).outputs.private_subnets | toJson  }}'
        cluster_endpoint_public_access: true #dev mode
        cluster_endpoint_private_access: true
        vpc_cni_custom_subnet: '{{ (atmos.Component "vpc" .stack).outputs.intra_subnets | toJson  }}'
        azs: '{{ (atmos.Component "vpc" .stack).outputs.azs | toJson }}'
        cluster_version: "1.30"
        # Enable EKS Add-ons
        enable_amazon_eks_aws_efs_csi_driver: true
        enable_amazon_eks_aws_ebs_csi_driver: true
        efs_vpc_cidr_blocks: '{{ (atmos.Component "vpc" .stack).outputs.private_subnets_cidr_blocks | toJson  }}'
        # Kubernetes Resources
        create_kubernetes_resources: false
        create_ssm_parameters: false
        # Blueprints Addons
        enable_aws_load_balancer_controller: true
        enable_karpenter: true
        enable_bottlerocket_update_operator: true
        tags:
          Environment: "dev"
          Owner: "team"