vars:
  stage: "dev"
  region: "us-gov-west-1"
  ami_id: "ami-08b9131e91f9f6c69"
  test_var: "{{ \"Hello, Atmos!\" }}"

components:
  terraform:
    vpc:
      vars:
        name: "dev-vpc"
        vpc_cidr: "10.200.0.0/16"
        secondary_cidr_blocks: ["100.64.0.0/16"]
        private_subnets:
          - "10.200.12.0/22"
          - "10.200.16.0/22"
          - "10.200.20.0/22"
        database_subnets:
          - "10.200.24.0/27"
          - "10.200.24.32/27"
          - "10.200.24.64/27"
        azs:
          - "us-gov-west-1a"
          - "us-gov-west-1b"
          - "us-gov-west-1c"
        single_nat_gateway: false
        enable_nat_gateway: false
        tags:
          Environment: "dev"
          Project: "example"
          Owner: "team"
          ManagedBy: "Terraform"
          Repo: "https://github.com/defenseunicorns/terraform-aws-vpc"
    # bastion:
    #   dependencies:
    #     terraform:
    #       - vpc  # Ensure vpc runs before bastion
    #   vars:
    #     name: "dev-bastion"
    #     vpc_id: '{{ (atmos.Component "vpc" "dev").outputs.vpc_id }}'
    #     instance_type: "t3.micro"
    #     subnet_id: '{{ index (atmos.Component "vpc" .stack).outputs.private_subnets 0 }}'
    #     tags:
    #       Environment: "dev"
    #       Owner: "team"
    eks:
      vars:
        cluster_name: "dev-eks"
        # aws_admin_usernames: [""]
        create_ssm_parameters: false
        vpc_id: '{{ (atmos.Component "vpc" "dev").outputs.vpc_id }}'
        azs: '{{ (atmos.Component "vpc" .stack).outputs.azs | toJson }}'
        private_subnet_ids: '{{ (atmos.Component "vpc" .stack).outputs.private_subnets | toJson  }}'
        control_plane_subnet_ids: '{{ (atmos.Component "vpc" .stack).outputs.private_subnets | toJson  }}'
        vpc_cni_custom_subnet: '{{ (atmos.Component "vpc" .stack).outputs.intra_subnets | toJson  }}'
        efs_vpc_cidr_blocks: ['{{ (atmos.Component "vpc" .stack).outputs.vpc_cidr_block | toJson  }}']
        tags:
          Environment: "dev"
          Owner: "team"