name: EKS
workflows:
  # Mission Init
  plan-init:
    stack: dev
    steps:
      - name: "init"
        command: terraform plan init
  apply-init:
    stack: dev
    steps:
      - name: "init"
        command: terraform apply init -auto-approve

  # VPC
  plan-vpc:
    stack: dev
    steps:
      - name: "init"
        command: terraform apply init -auto-approve
      - name: "vpc"
        command: terraform plan vpc
  apply-vpc:
    stack: dev
    steps:
      - name: "init"
        command: terraform apply init -auto-approve
      - name: "vpc"
        command: terraform apply vpc -auto-approve
  destroy-vpc:
    stack: dev
    steps:
      - name: "init"
        command: terraform apply init -auto-approve
      - name: "vpc"
        command: terraform destroy vpc -auto-approv

  # EKS
  plan-eks:
    stack: dev
    steps:
      - name: "init"
        command: terraform apply init -auto-approve
      - name: "vpc"
        command: terraform apply vpc -auto-approve
      #- name: "bastion"
      #command: terraform apply bastion -auto-approve
      - name: "eks"
        command: terraform plan eks
  apply-eks:
    stack: dev
    steps:
      - name: "init"
        command: terraform apply init -auto-approve
      - name: "vpc"
        command: terraform apply vpc -auto-approve
      - name: "eks"
        command: terraform apply eks -auto-approve
  destroy-eks:
    stack: dev
    steps:
      - name: "init"
        command: terraform apply init -auto-approve
      - name: "eks"
        command: terraform destroy eks -auto-approve
      #- name: "vpc"
      #command: terraform destroy vpc -auto-approve

  # UDS Keycloak
  plan-keycloak:
    stack: dev
    steps:
      - name: "init"
        command: terraform apply init -auto-approve
      - name: "vpc"
        command: terraform apply vpc -auto-approve
      #- name: "bastion"
      #command: terraform apply bastion -auto-approve
      - name: "keycloak"
        command: terraform plan uds-keycloak
  apply-keycloak:
    stack: dev
    steps:
      - name: "init"
        command: terraform apply init -auto-approve
      - name: "vpc"
        command: terraform apply vpc -auto-approve
      - name: "keycloak"
        command: terraform apply uds-keycloak -auto-approve
  destroy-keycloak:
    stack: dev
    steps:
      - name: "init"
        command: terraform apply init -auto-approve
      - name: "keycloak"
        command: terraform destroy uds-keycloak -auto-approve
      #- name: "vpc"
      #command: terraform destroy vpc -auto-approve
