# If the workflow trigger is "pull_request", auto-succeed required checks.
# these tests will be handled in the merge_group workflow (merge queue)
name: auto-success

on:
  pull_request:

jobs:

  report-status:
    runs-on:  ubuntu-latest
    steps:
      - name: debug
        uses: hmarr/debug-action@v2

      - name: update e2e-commercial-insecure success
        uses: docker://cloudposse/github-status-updater
        with:
          args: "-action update_state -state success -ref ${{ env.REPO_SHA }} -repo ${{ env.REPO_NAME }}"
        env:
          REPO_SHA: ${{ github.event.client_payload.pull_request.head.sha || github.event.pull_request.head.sha || github.sha }}
          REPO_NAME: ${{ github.event.client_payload.github.payload.repository.name || github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT:  "test / e2e-commercial-insecure"
          GITHUB_DESCRIPTION: "auto-success, not a real status to merge into main"
          GITHUB_TARGET_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GITHUB_REF: ${{ github.event.client_payload.pull_request.head.ref || github.event.pull_request.head.ref || github.ref_name }}
          GITHUB_OWNER: ${{ github.event.client_payload.github.payload.repository.owner.login || github.repository_owner }}

      - name: update e2e-govcloud-secure success
        uses: docker://cloudposse/github-status-updater
        with:
          args: "-action update_state -state success -ref ${{ env.REPO_SHA }} -repo ${{ env.REPO_NAME }}"
        env:
          REPO_SHA: ${{ github.event.client_payload.pull_request.head.sha || github.event.pull_request.head.sha || github.sha }}
          REPO_NAME: ${{ github.event.client_payload.github.payload.repository.name || github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT:  "test / e2e-govcloud-secure"
          GITHUB_DESCRIPTION: "auto-success, not a real status to merge into main"
          GITHUB_TARGET_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GITHUB_REF: ${{ github.event.client_payload.pull_request.head.ref || github.event.pull_request.head.ref || github.ref_name }}
          GITHUB_OWNER: ${{ github.event.client_payload.github.payload.repository.owner.login || github.repository_owner }}
