# gh workflow run matrix_debug.yml --ref ci/make-e2e-flexible
name: matrix_debug

on: workflow_dispatch

defaults:
  run:
    shell: bash -exo pipefail {0}

jobs:
  e2e-test:
    uses: defenseunicorns/delivery-github-actions-workflows/.github/workflows/e2e-test.yml@ci/make-e2e-test-accept-arbitrary-targets
    secrets:
      APPLICATION_ID: ${{ secrets.NARWHAL_BOT_APP_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.NARWHAL_BOT_SECRET }}
      AWS_COMMERCIAL_ROLE_TO_ASSUME: ${{ secrets.NARWHAL_AWS_COMMERCIAL_ROLE_TO_ASSUME }}
      AWS_GOVCLOUD_ROLE_TO_ASSUME: ${{ secrets.NARWHAL_AWS_GOVCLOUD_ROLE_TO_ASSUME }}
    with:
      e2e-test-matrix: ${{ (fromJson(github.event.client_payload.slash_command_args.named).make == null || fromJson(github.event.client_payload.slash_command_args.named).region == null) && null || format('[{{"make-target":"{0}", "region":"{1}"}}]', github.event.client_payload.slash_command_args.named.make, github.event.client_payload.slash_command_args.named.region) }}
