# triggers on merge_group and pull_request events

name: pr-merge-queue
on:
  merge_group:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash -eo pipefail {0}

jobs:
  report-success-status: # on PRs, report success for required status checks. this allows the testing to only run inside the merge queue. "status-checks" is a json array of status checks to report the status for.
    if: github.event_name == 'pull_request'
    uses: defenseunicorns/delivery-github-actions-workflows/.github/workflows/report-status.yml@ci/merge-queue-workflow
    secrets:
      APPLICATION_ID: ${{ secrets.NARWHAL_BOT_APP_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.NARWHAL_BOT_SECRET }}
    with:
      status-checks: '["pr-merge-queue / e2e-commercial-insecure", "pr-merge-queue / e2e-govcloud-secure"]'
      description: 'automated report success in pull request'
      status: 'success'

  e2e-commercial-insecure:
    if: github.event_name == 'merge_group'
    runs-on: ubuntu-latest
    steps:
      - name: Run E2E commercial insecure tests
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/e2e@ci/merge-queue-workflow
        with:
          application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
          application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}
          token: ${{ secrets.TOKEN }}
          role-to-assume: ${{ secrets.NARWHAL_AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          region: us-east-2
          github-context: "test / e2e-commercial-insecure"
          test-to-run: "insecure"
          send-slack-message: "false"

  # Run the E2E secure tests on the govcloud account in the merge queue if this is a release-please branch that merges into main
  e2e-govcloud-secure:
    if: github.event_name == 'merge_group' && github.ref_name == 'release-please--branches--main'
    runs-on: ubuntu-latest
    steps:
    - name: Run E2E govcloud secure tests
      uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/e2e@ci/merge-queue-workflow
      with:
        application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
        application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}
        token: ${{ secrets.TOKEN }}
        role-to-assume: ${{ secrets.NARWHAL_AWS_GOVCLOUD_ROLE_TO_ASSUME }}
        region: us-gov-east-1
        github-context: "test / e2e-govcloud-secure"
        test-to-run: "secure"
        send-slack-message: "true"
