# triggers on merge_group and pull_request events

name: pr-merge-queue
on:
  merge_group:
  pull_request:
    branches:
      - merge-queue

defaults:
  run:
    shell: bash -eo pipefail {0}

jobs:
  short-circuit:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - run: exit 1

  e2e-commercial-insecure:
    needs: short-circuit
    runs-on: ubuntu-latest
    if: github.event_name == 'merge_group'
    steps:
      - name: Run E2E Tests
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/context@ci/merge-queue-workflow  #this will fail
        with:
          application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
          application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}
          github-context: "pr-merge-queue / e2e-commercial-insecure"

  # Run the E2E secure tests on the govcloud account in the merge queue if this is a release-please branch into main
  e2e-govcloud-secure:
    needs: short-circuit
    runs-on: ubuntu-latest
    if: github.event_name == 'merge_group' && github.ref_name == 'ci/refactor_for_merge_queue_testing'
    steps:
      - name: Run E2E Tests
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/context@ci/merge-queue-workflow #this will fail
        with:
          application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
          application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}
          github-context: "pr-merge-queue / e2e-govcloud-secure"

  # short-circuit-pull-request-event:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'pull_request'
  #   steps:
  #     - name: Run E2E Tests
  #       uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/pull_request_status_check_dummy@ci/merge-queue-workflow  #this will fail
  #       with:
  #         application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
  #         application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}
  #         github-context: "pr-merge-queue-test / e2e-commercial-insecure"

  # Run the E2E insecure tests on the commercial account in the merge queue
  # e2e-commercial-insecure:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'merge_group'
  #   steps:
  #     - name: Run E2E Tests
  #       uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/e2e@main
  #       with:
  #         application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
  #         application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}
  #         role-to-assume: ${{ secrets.NARWHAL_AWS_COMMERCIAL_ROLE_TO_ASSUME }}
  #         region: us-east-2
  #         github-context: "pr-merge-queue-test / e2e-commercial-insecure"
  #         test-to-run: "insecure"

  # # Run the E2E secure tests on the govcloud account in the merge queue if this is a release-please branch into main
  # e2e-govcloud-secure:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'merge_group' && github.ref_name == 'release-please--branches--main'
  #   steps:
  #     - name: Run E2E Tests
  #       uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/e2e@main
  #       with:
  #         application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
  #         application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}
  #         token: ${{ secrets.TOKEN }}
  #         role-to-assume: ${{ secrets.NARWHAL_AWS_GOVCLOUD_ROLE_TO_ASSUME }}
  #         region: us-gov-east-1
  #         github-context: "pr-merge-queue-test / e2e-govcloud-secure"
  #         test-to-run: "secure"
