name: pre-commit-all

on:
  push:
    branches:
      - main
  schedule:
    - cron: '26 21 * * 5'

jobs:
  pre-commit-golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: all
