name: run-pre-commit

on:
  pull_request:
    paths:
      - "renovate.json5"
      - "Makefile"
      - ".pre-commit-config.yaml"

jobs:
  pre-commit-renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: renovate
