name: pre-commit-terraform

on:
  pull_request:
    paths:
      - "**.tf"
      - "Makefile"
      - ".tool-versions"
      - ".pre-commit-config.yaml"
      - ".checkov.yml"
      - ".tflint.hcl"

jobs:
  pre-commit-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: terraform


