name: pre-commit-golang

on:
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "Makefile"
      - ".tool-versions"
      - ".pre-commit-config.yaml"
      - ".golangci.yml"

jobs:
  pre-commit-golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: golang
