name: pre-commit-common

on:
  pull_request:

jobs:
  pre-commit-common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: common
