# Attribution for a bunch of this goes to CloudPosse
# https://github.com/cloudposse/actions/blob/master/.github/workflows/test-command.yml

name: test
on:
  repository_dispatch:
    types: [test-command]
  push:
    branches:
      - main
      - feature/include-govcloud-in-tests-2

permissions:
  id-token: write
  contents: read

defaults:
  run:
    # We need -e -o pipefail for consistency with GitHub Actions' default behavior
    shell: bash -e -o pipefail {0}

jobs:
  # Parse the command, so we can decide which tests to run. Examples: "/test all", "/test validate", "/test e2e"
  # We can do as many of these as we want to get as granular as we want.
  parse:
    runs-on: ubuntu-latest
    outputs:
      run-ping: ${{ steps.parse.outputs.run-ping }}
      run-e2e: ${{ steps.parse.outputs.run-e2e }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Parse Args
        id: parse
        uses: ./.github/actions/parse-test

  # Update the comment that triggered the /test command to show the run url
  comment:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Update Comment
        uses: ./.github/actions/comment

  # Do a simple ping/pong status update to validate things are working
  ping:
    runs-on: ubuntu-latest
    needs: parse
    if: needs.parse.outputs.run-ping == 'true'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Ping Test
        uses: ./.github/actions/ping

  # Run the E2E tests on the commercial account
  e2e-commercial:
    runs-on: ubuntu-latest
    needs: parse
    if: needs.parse.outputs.run-e2e == 'true'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run E2E Tests
        uses: ./.github/actions/e2e
        with:
          account: commercial

  # Run the E2E tests on the govcloud account
  e2e-govcloud:
    runs-on: ubuntu-latest
    needs: parse
    if: needs.parse.outputs.run-e2e == 'true'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run E2E Tests
        uses: ./.github/actions/e2e
        with:
          account: govcloud
